### ISSUE TITLE
pip dependencies `cc-torch` and `detectron2` in environment.yml not directly installable 

### ISSUE THREAD

**Issue by kuldeepbrd1** [neuroailab/EISEN#1]
Setting up a conda env with the `environment.yml` fails

In the env file, `cc-torch` and `detectron2` fails. 
https://github.com/neuroailab/EISEN/blob/331d8bf97e62db82bc0da75474825d8365f67f12/environment.yml#L79
https://github.com/neuroailab/EISEN/blob/331d8bf97e62db82bc0da75474825d8365f67f12/environment.yml#L83

This is likely because `environment.yml` file contains pip dependencies that were installed from local project for [detectron2](https://github.com/facebookresearch/Detectron2/tree/v0.6) and [cc_torch](https://github.com/neuroailab/EISEN/tree/main/core/utils/Connected_components_PyTorch)

These could be removed from environment.yml file. Although trivial, it probably also helps to add quick instructions to install detectron2/cc_torch in the README.

**Comment by madratman** [comment]
in addition, raft and cc_torch could be just git submodules / you can add instructions in readme wrt how to install them 
it is hard to tell if there's an actual diff in the cc_torch and raft subdirs with the original repos

**Comment by Davidyao99** [comment]
I am using a windows machine and some of the packages are unresolved from environment.yml. Any tips on how to resolve this? Thank you!

**Comment by honglin-chen** [comment]
Hi @kuldeepbrd1 @madratman @Davidyao99, I apologize for the difficulty in installing the dependencies. I'm working on updating the codebase along with more detailed installing instructions. I'll release the update in the next two days. I'm sorry again for the inconvenience. Thank you for your interest in our work.

**Comment by honglin-chen** [comment]
Hi @kuldeepbrd1 @madratman @Davidyao99, I've updated the [README.md](https://github.com/neuroailab/EISEN/blob/main/README.md) with specific instructions on how to install `cc-torch` and `detectron2`.  More specifically, these two packages can be installed via the following commands, after installing `environment.yml`:

```
pip install 'git+https://github.com/zsef123/Connected_components_PyTorch.git'
pip install 'git+https://github.com/facebookresearch/detectron2.git@5aeb252b194b93dc2879b4ac34bc51a31b5aee13'
```
In addition, I've also updated the training dataset and codebase. If you have downloaded the previous version of the dataset, you might need to pull the most recent version of the code and re-download the new version of the dataset using the links specified in the [README.md](https://github.com/neuroailab/EISEN/blob/main/README.md). 

Thank you again. Please let me know if you run into other issues.

**Comment by madratman** [comment]
Thanks I'll give it a shot. 
I think you might want to delete this folder then? https://github.com/neuroailab/EISEN/tree/main/core/utils/Connected_components_PyTorch

**Comment by honglin-chen** [comment]
Hi @madratman, you are right. Thank you for the suggestion. I've deleted the folder and updated the main branch.
