### ISSUE TITLE
main.py does not work

### ISSUE THREAD

**Issue by madratman** [neuroailab/EISEN#3]
after fixing #1, I get this error:
![image](https://user-images.githubusercontent.com/6305323/186800976-a14ca641-72fd-4d36-96b2-3336235d28a7.png)

This is happening as the dataset is empty

debugging more, I think the issue is datasets.py L28:
![image](https://user-images.githubusercontent.com/6305323/186801211-9d860c2d-eb92-423e-a23b-e422c6ed7ab0.png)
![image](https://user-images.githubusercontent.com/6305323/186801265-763abc95-90e2-4fcb-b37f-370c7ec352d9.png)

so the glob line has an error

this is what the dataset looks like:

```
$ tree datasets/Playroom -L 3
datasets/Playroom
├── meta.json
├── train
│   ├── images
│   │   ├── model_split_0
│   │   ├── model_split_1
│   │   ├── model_split_10
│   │   ├── model_split_11
│   │   ├── model_split_12
│   │   ├── model_split_13
│   │   ├── model_split_14
│   │   ├── model_split_15
│   │   ├── model_split_16
│   │   ├── model_split_17
│   │   ├── model_split_18
│   │   ├── model_split_19
│   │   ├── model_split_2
│   │   ├── model_split_20
│   │   ├── model_split_21
│   │   ├── model_split_22
│   │   ├── model_split_23
│   │   ├── model_split_24
│   │   ├── model_split_25
│   │   ├── model_split_26
│   │   ├── model_split_27
│   │   ├── model_split_28
│   │   ├── model_split_29
│   │   ├── model_split_3
│   │   ├── model_split_30
│   │   ├── model_split_31
│   │   ├── model_split_4
│   │   ├── model_split_5
│   │   ├── model_split_6
│   │   ├── model_split_7
│   │   ├── model_split_8
│   │   └── model_split_9
│   └── segments
│       ├── model_split_0
│       ├── model_split_1
│       ├── model_split_10
│       ├── model_split_11
│       ├── model_split_12
│       ├── model_split_13
│       ├── model_split_14
│       ├── model_split_15
│       ├── model_split_16
│       ├── model_split_17
│       ├── model_split_18
│       ├── model_split_19
│       ├── model_split_2
│       ├── model_split_20
│       ├── model_split_21
│       ├── model_split_22
│       ├── model_split_23
│       ├── model_split_24
│       ├── model_split_25
│       ├── model_split_26
│       ├── model_split_27
│       ├── model_split_28
│       ├── model_split_29
│       ├── model_split_3
│       ├── model_split_30
│       ├── model_split_31
│       ├── model_split_4
│       ├── model_split_5
│       ├── model_split_6
│       ├── model_split_7
│       ├── model_split_8
│       └── model_split_9
└── val
    ├── images
    │   ├── model_split_0
    │   ├── model_split_1
    │   ├── model_split_2
    │   └── model_split_3
    └── segments
        ├── model_split_0
        ├── model_split_1
        ├── model_split_2
        └── model_split_3

78 directories, 1 file
```

So. I added the "train" and "val" prefixes:
![image](https://user-images.githubusercontent.com/6305323/186801449-4f6aab14-5184-44d4-924c-7e5ad0188cc8.png)

However, now our glob is list of folders (instead of pngs)
![image](https://user-images.githubusercontent.com/6305323/186801641-cbe3585a-ce4f-4173-9ff1-703da8e6420f.png)

the __getitem__() fn seems to suggest you are taking every 5th frame (as also mentioned in the paper)
however the dataset format does not seem to be like that:
![image](https://user-images.githubusercontent.com/6305323/186801730-7fdf6b33-2c31-43ce-91df-6575c47db246.png)

**Comment by Davidyao99** [comment]
Hi, may I ask how did you manage to download the dependencies with conda? I am having issues with ResolvePackageNotFound:. I am using conda on windows and not sure how to overcome this ;(

**Comment by madratman** [comment]
Hey, see my PR here https://github.com/neuroailab/EISEN/pull/2. 
I am on linux, but I think PR#2 should fix things for linux as well most probably.
