### ISSUE TITLE
Bootstrapping with teacher / student model

### ISSUE THREAD

**Issue by Davidyao99** [neuroailab/EISEN#4]
Hi, I am a little confused about how the bootstrapping of the teacher/student model works. I cannot seem to find the relevant portion in the code. This is my idea of how it works from the paper:

Train the model for a few iterations on the entire video. Save the feature outputs of this model (teacher). Initialize a new model (student) using weights from the teacher model, which will train a few iterations again on the entire video. This time using the outputs of the teacher model as a guide. Repeat process.

Is my understanding correct? Thank you!! Great work ;))

**Comment by honglin-chen** [comment]
Your understanding is correct! I'm still re-implementing the bootstrapping training process in this repository, as mentioned in README.md. I will release the code as soon as it's ready. Sorry for the delay.

**Comment by Davidyao99** [comment]
No problem, thanks for responding!!
